# This is a basic workflow to help you get started with Actions

name: CI

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build rendertron
      run: docker build -t render/tron .         
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: render/tron 
          args: --severity-threshold=high
      - name: Run anchore
        uses: anchore/scan-action@v2
        with:
         image: render/tron
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: render/tron



