# This is a basic workflow to help you get started with Actions

name: CI

on: [push, workflow_dispatch]
jobs:    
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build rendertron
        run: docker build -t render/tron .    
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: render/tron 
      - name: Run anchore
        if: ${{ always() }
        uses: anchore/scan-action@v2
        with:
         image: render/tron
      - name: Run Trivy vulnerability scanner
        if: ${{ always() }
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: render/tron
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build rendertron
        run: |
          docker build -t render/tron . 
          docker run render/tron  find . -name chrome -exec {} --version \;   

